# Generated by Django 4.1 on 2023-03-15 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pvoucher', '0002_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='audience',
            field=models.ForeignKey(default='doyows', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
