# Generated by Django 4.1 on 2023-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0003_alter_notes_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='audience',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
