# Generated by Django 4.1 on 2023-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0004_alter_notes_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='audience',
            field=models.CharField(default='everyone', max_length=20),
            preserve_default=False,
        ),
    ]
