# Generated by Django 4.1 on 2023-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0005_alter_notes_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('desc1', models.CharField(max_length=200)),
                ('desc2', models.CharField(blank=True, max_length=200)),
                ('desc3', models.CharField(blank=True, max_length=200)),
                ('amount1', models.IntegerField(max_length=10)),
                ('amount2', models.IntegerField(blank=True, max_length=10)),
                ('amount3', models.IntegerField(blank=True, max_length=10)),
                ('total', models.IntegerField(max_length=10)),
                ('payment_mode', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('invoice_no', models.CharField(default='n/a', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField()),
            ],
        ),
    ]
