# Generated by Django 4.1 on 2023-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0006_projects_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='amount2',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='amount3',
            field=models.IntegerField(max_length=10),
        ),
    ]
