# Generated by Django 4.1 on 2023-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0008_alter_vouchers_amount2_alter_vouchers_amount3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='amount2',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='amount3',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
