# Generated by Django 4.1 on 2023-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0010_alter_vouchers_amount1_alter_vouchers_amount2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='amount2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='amount3',
            field=models.IntegerField(null=True),
        ),
    ]
