# Generated by Django 4.1 on 2023-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0013_alter_vouchers_amount1_alter_vouchers_amount2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='amount3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
