# Generated by Django 4.1 on 2023-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0014_alter_vouchers_amount3'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='approved',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='prepared',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
