# Generated by Django 4.1 on 2023-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0015_vouchers_approved_vouchers_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
