# Generated by Django 4.1 on 2023-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0016_vouchers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
