# Generated by Django 4.1 on 2023-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvoucher', '0017_vouchers_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='read',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
